# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes: 
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - /tmp/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example

  app:
    image: oplin
    volumes: 
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    working_dir: /app
    environment:
      OPLIN_TEST_DB_HOST: db
    command: go run cmd/oplin/main.go -db_host db 
