// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type LineageDataset struct {
	ID               int64
	CurrentVersionID sql.NullInt64
	NamespaceID      int64
	Name             string
	Facets           pqtype.NullRawMessage
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
}

type LineageDatasetNamespace struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type LineageDatasetVersion struct {
	ID          int64
	DatasetID   int64
	NamespaceID int64
	Name        string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type LineageField struct {
	ID               int64
	DatasetVersionID int64
	Name             string
	DataType         string
	Description      sql.NullString
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
}

type LineageJob struct {
	ID               int64
	CurrentVersionID sql.NullInt64
	NamespaceID      int64
	Name             string
	Facets           pqtype.NullRawMessage
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
}

type LineageJobNamespace struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type LineageJobVersion struct {
	ID          int64
	JobID       int64
	NamespaceID int64
	Name        string
	Facets      pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type LineageLifecycleStateChange struct {
	ID        int64
	DatasetID int64
	Change    sql.NullString
	Namespace sql.NullString
	Name      sql.NullString
	DataType  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type LineageRequest struct {
	ID        int64
	Payload   json.RawMessage
	CreatedAt time.Time
}

type LineageRun struct {
	ID                  int64
	RunUuid             uuid.UUID
	JobVersionID        int64
	ParentRunID         sql.NullInt64
	LastEventType       int32
	Facets              pqtype.NullRawMessage
	StartedAt           sql.NullTime
	EndedAt             sql.NullTime
	NominalStartedAt    sql.NullTime
	NominalEndedAt      sql.NullTime
	ErrorMessage        sql.NullString
	ProgrammingLanguage sql.NullString
	Stacktrace          sql.NullString
	CreatedAt           time.Time
	UpdatedAt           sql.NullTime
}

type LineageRunDatasetVersion struct {
	RunID            int64
	DatasetVersionID int64
	IoType           int32
	DatasetFacets    pqtype.NullRawMessage
	IoFacets         pqtype.NullRawMessage
	CreatedAt        time.Time
}

type LineageRunEvent struct {
	ID        int64
	RunID     int64
	EventType int32
	EventTime time.Time
	Facets    pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
