name: unit-tests
on: push

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest
    container: golang

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make dep 

      - name: Setup Test Database
        run: make init-test-db
        env:
          OPLIN_TEST_DB_HOST: db
          OPLIN_TEST_DB_NAME: postgres
          OPLIN_TEST_DB_PASSWORD: postgres
          OPLIN_TEST_DB_USER: postgres

      - name: Run tests
        run: make tests
        env:
          OPLIN_TEST_DB_HOST: db

